#!/bin/sh

### BEGIN INIT INFO
# Provides:               hsn2-swf-cve
# Required-Start:         $remote_fs
# Required-Stop:          $remote_fs
# Default-Start:          2 3 4 5
# Default-Stop:           0 1 6
# Short-Description:      Start/Stop the HSN2 SWF-CVE Analyzer
# Description:            Start/Stop the HSN2 SWF-CVE Analyzer Service daemon.
### END INIT INFO

NAME="HSN2 SWF-CVE Analyzer"
HSN2_COMPONENT="swf-cve"
MAINCLASS="pl.nask.hsn2.service.SwfService"
CONFFILE=/etc/hsn2/swf-cve.conf

HSN2_JMX_PORT=1110

. /lib/hsn2/init-functions-java

prepare_start() {
	HSN2_COMPONENT_PARAMS="--connector $BROKER_ADDRESS \
		--dataStore http://$DATASTORE_ADDRESS \
		--maxThreads $MAX_THREADS \
		-plugins $HSN2_COMPONENT_HOME/plugins"
}

choose_java_service_action $@

exit $?
