#!/bin/sh

### BEGIN INIT INFO
# Provides:               hsn2-swf-cve
# Required-Start:
# Required-Stop:
# Default-Start:          2 3 4 5
# Default-Stop:           0 1 6
# Short-Description:      Start/Stop the HSN2 SWF-CVE Analyzer
# Description:            Start/Stop the HSN2 SWF-CVE Analyzer Service daemon.
### END INIT INFO

NAME="HSN2 SWF-CVE Analyzer"
HSN2_COMPONENT="swf-cve"

HSN2_COMPONENT_HOME="/opt/hsn2/$HSN2_COMPONENT"
PIDFILE="/var/run/hsn2-$HSN2_COMPONENT.pid"

HSN2_COMPONENT_PARAMS="-connector 127.0.0.1 \
	-dataStore http://localhost:8080 \
	-plugins $HSN2_COMPONENT_HOME/plugins"

HSN2_JVM_PARAMS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1110"

MAINCLASS="pl.nask.hsn2.service.SwfService"

JSVCBIN=`which jsvc`

. /lib/lsb/init-functions

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

# We need openjdk runtime.
require_java_runtime openjdk

# find_jars commons-io slf4j-log4j12 slf4j-api log4j-1.2 commons-daemon

use_jsvc_wrapper () {
	#log_daemon_msg "using jsvc..."
	case "$1" in
		start)
			log_daemon_msg "Starting" "$NAME"
			$JSVCBIN -home $JAVA_HOME -wait 30 -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $JAVA_CLASSPATH:$HSN2_COMPONENT_HOME/lib:$HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS $HSN2_COMPONENT_PARAMS
			
			log_end_msg $?
			return $?
			;;
		stop)
			log_daemon_msg "Stopping" "$NAME"
			$JSVCBIN -home $JAVA_HOME -stop -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $JAVA_CLASSPATH:$HSN2_COMPONENT_HOME/lib:$HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS 

			log_end_msg $?
			return $?
			;;
		status)
			status_of_proc -p $PIDFILE $JSVCBIN "$NAME" && return 0 || return $?
			;;
	esac
		
return 0
}
	

use_jsvc_wrapper $@

exit $?

